
const CHATCONST = {
    DASHBOARD: 0,
    DETAILVIEW: 1,
    DETAILEDIT: 2,
    DETAILIMAGE: 3,
    DETAILdESCRIPTION: 4,
}

const CHAT_CATEGORY = {
    CHARACTER: 0,
    MONSTER: 1,
    SPELL: 2,
    BACKGROUND: 3,
}

const LOCALSTORAGE_USERSESSION = 'GameScribe Token'

export { CHATCONST, CHAT_CATEGORY, LOCALSTORAGE_USERSESSION }