
const CHATCONST = {
    DASHBOARD: 0,
    DETAILVIEW: 1,
    DETAILEDIT: 2,
    DETAILIMAGE: 3,
    DETAILdESCRIPTION: 4,
}

const LOCALSTORAGE_USERSESSION = 'GameScribe Token'

export { CHATCONST, LOCALSTORAGE_USERSESSION }